// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddPhoto(arg1:number,arg2:string,arg3:string):Promise<number>;

export function CreateExpenseByTripId(arg1:number,arg2:models.ExpenseInput):Promise<number>;

export function CreateItineraryByTripId(arg1:number,arg2:models.ItineraryInput):Promise<number>;

export function CreateLinkByTripId(arg1:number,arg2:models.LinkInput):Promise<number>;

export function CreateNoteByTripId(arg1:number,arg2:models.NoteInput):Promise<number>;

export function CreateTrip(arg1:models.TripInput):Promise<number>;

export function DeleteAllPhotosByTripId(arg1:number):Promise<void>;

export function DeleteExpenseById(arg1:number):Promise<void>;

export function DeleteItineraryById(arg1:number):Promise<void>;

export function DeleteLinkById(arg1:number):Promise<void>;

export function DeleteNoteById(arg1:number):Promise<void>;

export function DeletePhotoById(arg1:number):Promise<void>;

export function DeleteTripById(arg1:number):Promise<void>;

export function GetAllTrips():Promise<Array<models.Trip>>;

export function GetExpenseById(arg1:number):Promise<models.Expense>;

export function GetExpensesByTripId(arg1:number):Promise<Array<models.Expense>>;

export function GetItinerariesByTripId(arg1:number):Promise<Array<models.Itinerary>>;

export function GetItineraryById(arg1:number):Promise<models.Itinerary>;

export function GetLinkById(arg1:number):Promise<models.Link>;

export function GetLinksByTripId(arg1:number):Promise<Array<models.Link>>;

export function GetNoteById(arg1:number):Promise<models.Note>;

export function GetNotesByTripId(arg1:number):Promise<Array<models.Note>>;

export function GetPhotoBase64(arg1:number):Promise<string>;

export function GetPhotoById(arg1:number):Promise<models.Photo>;

export function GetPhotosByTripId(arg1:number):Promise<Array<models.Photo>>;

export function GetTripByID(arg1:number):Promise<models.Trip>;

export function GetWebSearchTrip():Promise<models.WebSearchResult>;

export function PickPhotoFile():Promise<string>;

export function Ping():Promise<string>;

export function UpdateCaptionByPhotoId(arg1:number,arg2:string):Promise<void>;

export function UpdateExpenseById(arg1:number,arg2:models.ExpenseInput):Promise<void>;

export function UpdateItineraryById(arg1:number,arg2:models.ItineraryInput):Promise<void>;

export function UpdateLinkById(arg1:number,arg2:models.LinkInput):Promise<void>;

export function UpdateNoteById(arg1:number,arg2:models.NoteInput):Promise<void>;

export function UpdateTripById(arg1:number,arg2:models.TripInput):Promise<void>;
