// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPhoto(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddPhoto'](arg1, arg2, arg3);
}

export function CreateExpenseByTripId(arg1, arg2) {
  return window['go']['main']['App']['CreateExpenseByTripId'](arg1, arg2);
}

export function CreateItineraryByTripId(arg1, arg2) {
  return window['go']['main']['App']['CreateItineraryByTripId'](arg1, arg2);
}

export function CreateLinkByTripId(arg1, arg2) {
  return window['go']['main']['App']['CreateLinkByTripId'](arg1, arg2);
}

export function CreateNoteByTripId(arg1, arg2) {
  return window['go']['main']['App']['CreateNoteByTripId'](arg1, arg2);
}

export function CreateTrip(arg1) {
  return window['go']['main']['App']['CreateTrip'](arg1);
}

export function DeleteAllPhotosByTripId(arg1) {
  return window['go']['main']['App']['DeleteAllPhotosByTripId'](arg1);
}

export function DeleteExpenseById(arg1) {
  return window['go']['main']['App']['DeleteExpenseById'](arg1);
}

export function DeleteItineraryById(arg1) {
  return window['go']['main']['App']['DeleteItineraryById'](arg1);
}

export function DeleteLinkById(arg1) {
  return window['go']['main']['App']['DeleteLinkById'](arg1);
}

export function DeleteNoteById(arg1) {
  return window['go']['main']['App']['DeleteNoteById'](arg1);
}

export function DeletePhotoById(arg1) {
  return window['go']['main']['App']['DeletePhotoById'](arg1);
}

export function DeleteTripById(arg1) {
  return window['go']['main']['App']['DeleteTripById'](arg1);
}

export function GenerateAITripPlan(arg1) {
  return window['go']['main']['App']['GenerateAITripPlan'](arg1);
}

export function GetAllTrips() {
  return window['go']['main']['App']['GetAllTrips']();
}

export function GetExpenseById(arg1) {
  return window['go']['main']['App']['GetExpenseById'](arg1);
}

export function GetExpensesByTripId(arg1) {
  return window['go']['main']['App']['GetExpensesByTripId'](arg1);
}

export function GetItinerariesByTripId(arg1) {
  return window['go']['main']['App']['GetItinerariesByTripId'](arg1);
}

export function GetItineraryById(arg1) {
  return window['go']['main']['App']['GetItineraryById'](arg1);
}

export function GetLinkById(arg1) {
  return window['go']['main']['App']['GetLinkById'](arg1);
}

export function GetLinksByTripId(arg1) {
  return window['go']['main']['App']['GetLinksByTripId'](arg1);
}

export function GetNoteById(arg1) {
  return window['go']['main']['App']['GetNoteById'](arg1);
}

export function GetNotesByTripId(arg1) {
  return window['go']['main']['App']['GetNotesByTripId'](arg1);
}

export function GetPhotoBase64(arg1) {
  return window['go']['main']['App']['GetPhotoBase64'](arg1);
}

export function GetPhotoById(arg1) {
  return window['go']['main']['App']['GetPhotoById'](arg1);
}

export function GetPhotosByTripId(arg1) {
  return window['go']['main']['App']['GetPhotosByTripId'](arg1);
}

export function GetTripByID(arg1) {
  return window['go']['main']['App']['GetTripByID'](arg1);
}

export function PickPhotoFile() {
  return window['go']['main']['App']['PickPhotoFile']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function UpdateCaptionByPhotoId(arg1, arg2) {
  return window['go']['main']['App']['UpdateCaptionByPhotoId'](arg1, arg2);
}

export function UpdateExpenseById(arg1, arg2) {
  return window['go']['main']['App']['UpdateExpenseById'](arg1, arg2);
}

export function UpdateItineraryById(arg1, arg2) {
  return window['go']['main']['App']['UpdateItineraryById'](arg1, arg2);
}

export function UpdateLinkById(arg1, arg2) {
  return window['go']['main']['App']['UpdateLinkById'](arg1, arg2);
}

export function UpdateNoteById(arg1, arg2) {
  return window['go']['main']['App']['UpdateNoteById'](arg1, arg2);
}

export function UpdateTripById(arg1, arg2) {
  return window['go']['main']['App']['UpdateTripById'](arg1, arg2);
}
