// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTrip(arg1) {
  return window['go']['main']['App']['CreateTrip'](arg1);
}

export function DeleteTripById(arg1) {
  return window['go']['main']['App']['DeleteTripById'](arg1);
}

export function GetAllTrips() {
  return window['go']['main']['App']['GetAllTrips']();
}

export function GetTripByID(arg1) {
  return window['go']['main']['App']['GetTripByID'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function UpdateTripById(arg1, arg2) {
  return window['go']['main']['App']['UpdateTripById'](arg1, arg2);
}
