// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateTrip(arg1:models.TripInput):Promise<number>;

export function DeleteTripById(arg1:number):Promise<void>;

export function GetAllTrips():Promise<Array<models.Trip>>;

export function GetTripByID(arg1:number):Promise<models.Trip>;

export function Ping():Promise<string>;

export function UpdateTripById(arg1:number,arg2:models.TripInput):Promise<number>;
